"""store local activity time and athlete offset

Revision ID: 1e548387ee49
Revises: 4fce8ff98f85
Create Date: 2026-08-29 21:05:53.900372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations but doesn't add the
# import itself, so it lives in the template.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e548387ee49'
down_revision: Union[str, Sequence[str], None] = '4fce8ff98f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('activities', sa.Column('start_date_local', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('utc_offset', sa.Integer(), nullable=True))
    op.add_column('athletes', sa.Column('utc_offset', sa.Integer(), nullable=True))

    # Every activity we have already stored carries Strava's full payload, so the local
    # clock is recoverable without re-fetching a single one. start_date_local arrives with a
    # trailing Z that Strava does not mean — it is wall clock — so the zone is stripped by
    # casting to a plain timestamp.
    op.execute("""
        UPDATE activities
        SET start_date_local = (raw_data->>'start_date_local')::timestamp,
            utc_offset = (raw_data->>'utc_offset')::double precision::integer
        WHERE raw_data ? 'start_date_local'
    """)

    # Each athlete starts out wherever their most recent activity was.
    op.execute("""
        UPDATE athletes a
        SET utc_offset = latest.utc_offset
        FROM (
            SELECT DISTINCT ON (owner_id) owner_id, utc_offset
            FROM activities
            WHERE utc_offset IS NOT NULL
            ORDER BY owner_id, start_date DESC
        ) AS latest
        WHERE latest.owner_id = a.athlete_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('athletes', 'utc_offset')
    op.drop_column('activities', 'utc_offset')
    op.drop_column('activities', 'start_date_local')
