"""push day notifications

Revision ID: 487d8c7abe76
Revises: 633dad0a3cff
Create Date: 2026-08-30 15:29:58.259795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations but doesn't add the
# import itself, so it lives in the template.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '487d8c7abe76'
down_revision: Union[str, Sequence[str], None] = '633dad0a3cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_day_notifications',
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('local_day', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.athlete_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'group_id', 'local_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_day_notifications')
    # ### end Alembic commands ###
