"""add target start date

Revision ID: 4fce8ff98f85
Revises: 41bf587c835e
Create Date: 2026-08-25 13:41:23.381482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations but doesn't add the
# import itself, so it lives in the template.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fce8ff98f85'
down_revision: Union[str, Sequence[str], None] = 'ad4372bbea0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate proposed a plain NOT NULL column, which cannot work on a table that
    # already holds targets. Add it nullable, backfill every existing target with the date it
    # was created (its effective start until now), then tighten the constraint.
    op.add_column('group_targets', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE group_targets SET starts_at = created_at WHERE starts_at IS NULL')
    op.alter_column('group_targets', 'starts_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_targets', 'starts_at')
    # ### end Alembic commands ###
