"""push subscriptions

Revision ID: 633dad0a3cff
Revises: 1e548387ee49
Create Date: 2026-08-30 15:01:13.923449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations but doesn't add the
# import itself, so it lives in the template.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '633dad0a3cff'
down_revision: Union[str, Sequence[str], None] = '1e548387ee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.athlete_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint')
    )
    op.create_index('ix_push_subscriptions_athlete', 'push_subscriptions', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_subscriptions_athlete', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
