"""add target start date

Revision ID: ad4372bbea0d
Revises: 41bf587c835e
Create Date: 2026-08-25 13:32:41.007386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations but doesn't add the
# import itself, so it lives in the template.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad4372bbea0d'
down_revision: Union[str, Sequence[str], None] = '41bf587c835e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
