"""empty revision, superseded by 4fce8ff98f85

Revision ID: ad4372bbea0d
Revises: 41bf587c835e
Create Date: 2026-08-25 13:32:41.007386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLModel emits sqlmodel.sql.sqltypes.* in autogenerated migrations but doesn't add the
# import itself, so it lives in the template.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad4372bbea0d'
down_revision: Union[str, Sequence[str], None] = '41bf587c835e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op.

    Generated empty by mistake and already released, so it stays in the chain: a database
    stamped here must still find this revision. The real change is in 4fce8ff98f85.
    """


def downgrade() -> None:
    """No-op — see upgrade()."""
